python: use the built-in API error handler for GSSAPI
ERROR: Failed to determine Copr username from authentication.
Error: Operation requires API authentication. See the 'AUTHENTICATION'
section in man copr-cli(1).
Error: Can't log-in using GSSAPI: Valid GSSAPI authentication supplied
for user 'coprteam', but this user doesn't exist in the Copr build
system.  Please log-in using the web-UI (without GSSAPI) first.