python: fix exception caused by default msg value
This is a small fixup after PR#2024. If an exception is raised simply
with `copr.v3.CoprRequestException()` we get another exception when
trying to get its string representation:

    self = CoprRequestException(None)

        def __str__(self):
    >       errors = self.result.error.split("\n")
    E       AttributeError: 'NoneType' object has no attribute 'split'

Merges: #2030