require python-psycopg2
in case you use python db backend you have to have psycopg driver

addressing:
Traceback (most recent call last):
  File "./manage.py", line 190, in <module>
    manager.run()
  File "/usr/lib/python2.7/site-packages/flask_script/__init__.py", line 351, in run
    result = self.handle(sys.argv[0], command, sys.argv[2:])
  File "/usr/lib/python2.7/site-packages/flask_script/__init__.py", line 324, in handle
    return command.handle(app, *positional_args, **command_namespace.__dict__)
  File "/usr/lib/python2.7/site-packages/flask_script/commands.py", line 143, in handle
    return self.run(*args, **kwargs)
  File "./manage.py", line 41, in run
    db.create_all()
  File "/usr/lib/python2.7/site-packages/flask_sqlalchemy.py", line 822, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/usr/lib/python2.7/site-packages/flask_sqlalchemy.py", line 814, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), tables=tables)
  File "/usr/lib/python2.7/site-packages/flask_sqlalchemy.py", line 763, in get_engine
    return connector.get_engine()
  File "/usr/lib/python2.7/site-packages/flask_sqlalchemy.py", line 443, in get_engine
    self._engine = rv = sqlalchemy.create_engine(info, **options)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 338, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 64, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 312, in dbapi
    psycopg = __import__('psycopg2')
ImportError: No module named psycopg2