[beaker-tests-sanity] remove the module properly
We need to specify stream and profile when removing a module to avoid:

    Error: Different stream enabled for module: testmodule

This commit should have been a part of PR#522, but somehow
disappeared during rebase.