fix failing test test_fail_on_missing_dash
_______________ TestCoprRepoGeneration.test_fail_on_missing_dash _______________

self = <test_coprs_ns.test_coprs_general.TestCoprRepoGeneration object at 0x4cdcd90>

    def test_fail_on_missing_dash(self):
        r = self.tc.get('/coprs/reponamewithoutdash/repo/')
        assert r.status_code == 404
>       assert 'Bad repository name' in r.data
E       assert 'Bad repository name' in '<!doctype html>\n<html>\n<head>\n  <title>Not Found</title>\n  <link rel=stylesheet type=text/css href="/static/copr.... <div class="page-inner">\n    \n  \n    Copr with name repo does not exist.\n  \n\n  </div>\n</div>\n</body>\n</html>'
E        +  where '<!doctype html>\n<html>\n<head>\n  <title>Not Found</title>\n  <link rel=stylesheet type=text/css href="/static/copr.... <div class="page-inner">\n    \n  \n    Copr with name repo does not exist.\n  \n\n  </div>\n</div>\n</body>\n</html>' = <Response 830 bytes [404 NOT FOUND]>.data

tests/test_views/test_coprs_ns/test_coprs_general.py:393: AssertionError