frontend: don't traceback for "module exists" error
We need to rollback() the session in case of exception, otherwise we
end-up with:
coprs.exceptions.DuplicateException: Module testmodule-beakertest-20210824084933 already exists
During handling of the above exception, another exception occurred:
...
DETAIL:  Key (copr_id, name, stream, version)=(44610, testmodule, beakertest, 20210824084933) already exists.
Seems like some implicit flush is causing this.