frontend: don't fail hard on update without package results
This is a typical situation when build fails, we have no RPMs and thus
no package result data:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/share/copr/coprs_frontend/coprs/views/misc.py", line 325, in decorated_function
    return f(*args, **kwargs)
  File "/usr/share/copr/coprs_frontend/coprs/views/backend_ns/backend_general.py", line 373, in update
    logic_cls.update_state_from_dict(obj, to_update[i])
  File "/usr/share/copr/coprs_frontend/coprs/logic/builds_logic.py", line 970, in update_state_from_dict
    BuildChrootResultsLogic.create_from_dict(
  File "/usr/share/copr/coprs_frontend/coprs/logic/builds_logic.py", line 1398, in create_from_dict
    for result in results["packages"]]
TypeError: 'NoneType' object is not subscriptable

Also removing one redundant assert call.

Relates: #1844