[backend] - add missing import
addressing:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/share/copr/backend/dispatcher.py", line 390, in run
    callback=mockremote.CliLogCallBack(quiet=True,logfn=chrootlogfile))
  File "/usr/share/copr/backend/mockremote.py", line 456, in __init__
    self.callback.log("Setting up builder: %s" % builder)
  File "/usr/share/copr/backend/mockremote.py", line 211, in log
    log(self.logfn, msg, self.quiet)
  File "/usr/share/copr/backend/mockremote.py", line 89, in log
    fcntl.flock(lfh, fcntl.LOCK_EX)
NameError: global name 'fcntl' is not define