frontend: fixup SubqueryPaginator for older sqlalchemy
The older sqlalchemy (at least version v1.3.24 on F33) doesn't like the
selecting primary key in the subquery, see the log below.  I fixed the
subquery so it uses the with_entities() instead, and while on it I
changed the logic so it is little bit easier to understand.

Request: GET https://copr-fe-dev.cloud.fedoraproject.org/api_3/build/list/?ownername=praiskup&projectname=module-testmodulev2-beakertest-20211001044252&packagename=perl-List-Compare
User: None
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/share/copr/coprs_frontend/coprs/views/apiv3_ns/__init__.py", line 69, in pagination_wrapper
    return f(*args, **kwargs)
  File "/usr/share/copr/coprs_frontend/coprs/views/apiv3_ns/__init__.py", line 56, in query_params_wrapper
    return f(*args, **kwargs)
  File "/usr/share/copr/coprs_frontend/coprs/views/apiv3_ns/apiv3_builds.py", line 116, in get_build_list
    paginator = SubqueryPaginator(query, models.Build, limit=paginator_limit, **kwargs)
  File "/usr/share/copr/coprs_frontend/coprs/views/apiv3_ns/__init__.py", line 171, in __init__
    self.subquery = self._create_subquery()
  File "/usr/share/copr/coprs_frontend/coprs/views/apiv3_ns/__init__.py", line 177, in _create_subquery
    def _create_subquery(self):
  File "<string>", line 2, in select
  File "<string>", line 2, in __init__
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 139, in warned
    return fn(*args, **kwargs)
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/sql/selectable.py", line 3117, in __init__
    for c in columns:
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/sql/operators.py", line 432, in __getitem__
    return self.operate(getitem, index)
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 226, in operate
    return op(self.comparator, *other, **kwargs)
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/sql/operators.py", line 432, in __getitem__
    return self.operate(getitem, index)
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/orm/properties.py", line 367, in operate
    return op(self.__clause_element__(), *other, **kwargs)
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/sql/operators.py", line 432, in __getitem__
    return self.operate(getitem, index)
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/sql/elements.py", line 762, in operate
    return op(self.comparator, *other, **kwargs)
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/sql/operators.py", line 432, in __getitem__
    return self.operate(getitem, index)
  File "<string>", line 1, in <lambda>
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/sql/type_api.py", line 68, in operate
    return o[0](self.expr, op, *(other + o[1:]), **kwargs)
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/sql/default_comparator.py", line 237, in _getitem_impl
    _unsupported_impl(expr, op, other, **kw)
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/sql/default_comparator.py", line 241, in _unsupported_impl
    raise NotImplementedError(
NotImplementedError: Operator 'getitem' is not supported on this expression