[cli] no need to set const with action=store_true
addressing:
Traceback (most recent call last):
  File "/usr/bin/copr-cli", line 9, in <module>
    load_entry_point('copr-cli==0.1.0', 'console_scripts', 'copr-cli')()
  File "/usr/lib/python2.7/site-packages/copr_cli/main.py", line 123, in main
    parser = setup_parser()
  File "/usr/lib/python2.7/site-packages/copr_cli/main.py", line 105, in setup_parser
    help="Don't wait for build")
  File "/usr/lib64/python2.7/argparse.py", line 1281, in add_argument
    action = action_class(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'const'