[backend] log real cause if ansible crash
addressing:
Process worker-builder:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/share/copr/backend/dispatcher.py", line 302, in run
    ip = self.spawn_instance()
  File "/usr/share/copr/backend/dispatcher.py", line 165, in spawn_instance
    shell=True)
  File "/usr/lib64/python2.7/subprocess.py", line 575, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command 'ansible-playbook -c ssh /home/copr/provision/builderpb.yml' returned non-zero exit status 2