fix test_coprs_builds failures
Can't use session.add due to:
AssertionError: A conflicting state is already present in the identity
map for key (<class 'coprs.models.Build'>, (1,))

Signed-off-by: Richard Marko <rmarko@fedoraproject.org>