convert eror message to binary text before emitting
The query comes from users and does not need to conform the regexp that we uses when creating a project.
In fact the string may contain unicode characters that cannot be converted to ascii stream.

Fixes: #3072

Addressing:
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/copr/coprs_frontend/coprs/views/misc.py", line 244, in wrapper
    copr = ComplexLogic.get_copr(username, coprname, with_mock_chroots=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/copr/coprs_frontend/coprs/logic/complex_logic.py", line 203, in get_copr
    raise ObjectNotFound(
coprs.exceptions.ObjectNotFound: Project t0xic0der/nvid\xe2\x80\xa6 does not exist.
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.12/logging/__init__.py", line 1163, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'ascii' codec can't encode character '\\u2026' in position 167: ordinal not in range(128)
Call stack:
  File "/usr/lib/python3.12/site-packages/flask/app.py", line 2552, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.12/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.12/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.12/site-packages/flask_restx/api.py", line 674, in error_router
    return original_handler(e)
  File "/usr/lib/python3.12/site-packages/flask/app.py", line 1676, in handle_user_exception
    return self.ensure_sync(handler)(e)
  File "/usr/share/copr/coprs_frontend/coprs/__init__.py", line 216, in handle_exceptions
    return error_handler.handle_error(error)
  File "/usr/share/copr/coprs_frontend/coprs/error_handlers.py", line 42, in handle_error
    app.logger.error("Response error: %s %s", code, message)
Message: 'Response error: %s %s'
Arguments: (404, 'Project t0xic0der/nvid\xe2\x80\xa6 does not exist.')
ERROR:coprs:Response error: 404 Project t0xic0der/nvid\xe2\x80\xa6 does not exist.