static_path -> static_folder
this has been renamed in flask 1.0

addressing:
Traceback (most recent call last):
  File "/usr/share/copr/mocks/frontend/app.py", line 19, in <module>
    app = flask.Flask(__name__, static_path='/static', static_folder=static_dir)
TypeError: __init__() got an unexpected keyword argument 'static_path'