frontend: run notify command with app context
This is required to properly generate content of a
`OutdatedChrootMessage`. Otherwise the clickable URL to project
settings cannot be create due to

    RuntimeError: Attempted to generate a URL without the application
    context being pushed. This has to be executed when application context
    is available.