rpmbuild: copr-distgit-client depends on python-six
Traceback (most recent call last):
  File "/usr/bin/copr-distgit-client", line 7, in <module>
    from copr_distgit_client import main
  File "/usr/lib/python3.12/site-packages/copr_distgit_client.py", line 14, in <module>
    from six.moves.urllib.parse import urlparse
ModuleNotFoundError: No module named 'six'