Use flask.flash(str(e)) instead of flash(e)
TypeError: InsufficientRightsException('Only owners may delete their
projects.',) is not JSON serializable

Signed-off-by: Richard Marko <rmarko@fedoraproject.org>