fixing test_fail_on_nonexistent_copr test
addressing:
    def test_fail_on_nonexistent_copr(self):
        r = self.tc.get('/coprs/bogus-nonexistent-repo/repo/')
        assert r.status_code == 404
>       assert 'bogus/nonexistent-repo does not exist' in r.data
E       assert 'bogus/nonexistent-repo does not exist' in '<!doctype html>\n<html>\n<head>\n  <title>Not Found</title>\n  <link rel=stylesheet type=text/css href="/static/copr.... <div class="page-inner">\n    \n  \n    Copr with name repo does not exist.\n  \n\n  </div>\n</div>\n</body>\n</html>'
E        +  where '<!doctype html>\n<html>\n<head>\n  <title>Not Found</title>\n  <link rel=stylesheet type=text/css href="/static/copr.... <div class="page-inner">\n    \n  \n    Copr with name repo does not exist.\n  \n\n  </div>\n</div>\n</body>\n</html>' = <Response 830 bytes [404 NOT FOUND]>.data