frontend: fix log.error string formatting
The curly-braces formating doesn't work without `.format()`,
unfortunatelly.

    TypeError: not all arguments converted during string formatting
    Call stack:
    File "/usr/bin/copr-frontend", line 120, in <module>
	app.cli()
    File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
	return self.main(*args, **kwargs)
    File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
	rv = self.invoke(ctx)
    File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
	return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/usr/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
	return ctx.invoke(self.callback, **ctx.params)
    File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
	return callback(*args, **kwargs)
    File "/usr/bin/copr-frontend", line 95, in wrapper
	sys.exit(bool(function(*args, **kwargs)))
    File "/usr/share/copr/coprs_frontend/commands/delete_outdated_chroots.py", line 14, in delete_outdated_chroots
	return delete_outdated_chroots_function(dry_run)
    File "/usr/share/copr/coprs_frontend/commands/delete_outdated_chroots.py", line 31, in delete_outdated_chroots_function
	app.logger.error("Refusing to delete {0}/{1} because any notification was sent about its deletion",
    Message: 'Refusing to delete {0}/{1} because any notification was sent about its deletion'
    Arguments: ('@copr/TEST1569009580679032184PackageScm', 'fedora-30-x86_64')