[backend] LogHandler: don't drop exc_info from LogRecord
Python's internals depend on that even before the message is
emitted, exception like this is raised:

    Traceback (most recent call last):
      File "/usr/lib64/python3.7/logging/__init__.py", line 1034, in emit
        msg = self.format(record)
      File "/usr/lib64/python3.7/logging/__init__.py", line 880, in format
        return fmt.format(record)
      File "/usr/lib64/python3.7/logging/__init__.py", line 623, in format
        if record.exc_info:
    AttributeError: 'LogRecord' object has no attribute 'exc_info'

Update test_helpers.py so we have also a small test for the
delivered message format.