backend: don't leave tracebacks in exception log entries alone
I reformated the log entry dump mechanism (commit 05b161e7659908c830d)
so the msg/args parameters are expanded before they go to redis.  But
exceptions can have msg/args as well - and it made the logs less
readable:

[2019-09-11 13:52:25,973][ ERROR][backend.worker-5-AARCH64][worker.py:do_job:218] Traceback (most recent call last):
  File "/usr/share/copr/backend/daemons/worker.py", line 211, in do_job
    mr.check_build_success() # raises if build didn't succeed
  File "/usr/share/copr/backend/mockremote/__init__.py", line 309, in check_build_success
    raise MockRemoteError("Build {} failed".format(self.job.task_id))
backend.exceptions.MockRemoteError: Build 846265-fedora-rawhide-aarch64 failed

vs.:
[2019-09-11 13:52:25,973][ ERROR][backend.worker-5-AARCH64][worker.py:do_job:218] Error during the build, host=38.145.48.106, build_id=846265, chroot=fedora-rawhide-aarch64
Traceback (most recent call last):
  File "/usr/share/copr/backend/daemons/worker.py", line 211, in do_job
    mr.check_build_success() # raises if build didn't succeed
  File "/usr/share/copr/backend/mockremote/__init__.py", line 309, in check_build_success
    raise MockRemoteError("Build {} failed".format(self.job.task_id))
backend.exceptions.MockRemoteError: Build 846265-fedora-rawhide-aarch64 failed

This commit fixes it, so it is easy to get oriented in the exception log
entries again.