require python-alembic
addressing:
Traceback (most recent call last):
  File "./manage.py", line 190, in <module>
    manager.run()
  File "/usr/lib/python2.7/site-packages/flask_script/__init__.py", line 351, in run
    result = self.handle(sys.argv[0], command, sys.argv[2:])
  File "/usr/lib/python2.7/site-packages/flask_script/__init__.py", line 324, in handle
    return command.handle(app, *positional_args, **command_namespace.__dict__)
  File "/usr/lib/python2.7/site-packages/flask_script/commands.py", line 143, in handle
    return self.run(*args, **kwargs)
  File "./manage.py", line 45, in run
    from alembic.config import Config
ImportError: No module named alembic.config