rpmbuild: open spec file as read-only
We never modify the spec file; therefore, it is safer to provide
python-specfile with a read-only file descriptor.  This prevents
tracebacks that occur when python-specfile attempts to open a read-only
file using default parameters (which defaults to 'r+' read-write).

Exception appeared during handling spec file: /var/lib/copr-rpmbuild/results/argparse-manpage.spec
Traceback (most recent call last):
  File "/usr/lib/python3.14/site-packages/copr_rpmbuild/helpers.py", line 418, in __init__
    self.spec = Specfile(path, macros=macros)
                ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.14/site-packages/specfile/specfile.py", line 105, in __init__
    self._file = Path(path).open("r+", **self.ENCODING_ARGS)
                 ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.14/pathlib/__init__.py", line 771, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/var/lib/copr-rpmbuild/results/argparse-manpage.spec'

Fixes: #4266