add BR python-blinker
Traceback (most recent call last):
  File "./manage.py", line 11, in <module>
    from coprs import app
  File "/builddir/build/BUILD/copr-frontend-git-0.a3c61e6/coprs_frontend/coprs/__init__.py", line 33, in <module>
    whooshee = Whooshee(app)
  File "/usr/lib/python2.7/site-packages/flask_whooshee.py", line 154, in __init__
    self.init_app(app)
  File "/usr/lib/python2.7/site-packages/flask_whooshee.py", line 161, in init_app
    models_committed.connect(self.on_commit, sender=app)
  File "/usr/lib/python2.7/site-packages/flask/signals.py", line 32, in _fail
    raise RuntimeError('signalling support is unavailable '
RuntimeError: signalling support is unavailable because the blinker library is not installed.