lint: initialize mypy
Ignore the .mypy_cache/ directories.

Also use global 'ignore_missing_imports = True', otherwise we'll see
a new errors like this:

  Error: MYPY_ERROR:
  coprs_frontend/coprs/auth.py:8: mypy[error]: Skipping analyzing "ldap": module is installed, but missing library stubs or py.typed marker

  Error: MYPY_ERROR:
  coprs_frontend/coprs/auth.py:9: mypy[error]: Skipping analyzing "openid_teams.teams": module is installed, but missing library stubs or py.typed marker

  Error: MYPY_NOTE:
  coprs_frontend/coprs/auth.py:9: mypy[note]: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports

We can find a better way to handle similar problems in the future.

Merges: #2353