frontend: give nice error instead of traceback
addressing:
Exception on /coprs/rhscl/python27/delete/ [POST]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/share/copr/coprs_frontend/coprs/views/misc.py", line 131, in decorated_function
    return f(*args, **kwargs)
  File "/usr/share/copr/coprs_frontend/coprs/views/coprs_ns/coprs_general.py", line 322, in copr_delete
    coprs_logic.CoprsLogic.delete(flask.g.user, copr)
  File "/usr/share/copr/coprs_frontend/coprs/logic/coprs_logic.py", line 162, in delete
    cls.raise_if_cant_delete(user, copr)
  File "/usr/share/copr/coprs_frontend/coprs/logic/coprs_logic.py", line 227, in raise_if_cant_delete
    if not user.admin and user != copr.owner:
AttributeError: 'NoneType' object has no attribute 'owner'