python: handle non-JSON 401 responses
Fix #4514

We will now show:

    Error: Operation requires API authentication. See the
    'AUTHENTICATION' section in man copr-cli(1).
    Error: Unauthorized

Instead of previous:

    Something went wrong:
    Error: Response is not in JSON format, there is probably a bug in
    the API code.