specify full prefix of http
because if we pass just http:/
mock will fail with
Traceback (most recent call last):
  File "/usr/bin/mockchain", line 336, in <module>
    main(sys.argv)
  File "/usr/bin/mockchain", line 235, in main
    res, msg =  add_local_repo(my_mock_config, my_mock_config, baseurl)
  File "/usr/bin/mockchain", line 95, in add_local_repo
    repoid=baseurl.split('//')[1].replace('/','_')
IndexError: list index out of range