[backend] fix traceback for non-serializable log message
In some cases we happen to log (through redis logger) objects
which are not json-serializable (by default).  This caused
ugly exceptions before, e.g.

   TypeError: Object of type 'Thread' is not JSON serializable

So let's provide some (even if not really nice) always-ready
serialization default so we never loose the whole log message
because of the traceback.