sleep and continue when frontend is not available
Addressing:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/copr/v3/requests.py", line 52, in send
    response = requests.request(**self._request_params)
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='copr.fedorainfracloud.org', port=443): Max retries exceeded with url: /api_3/project?ownername=rpmsoftwaremanagement&projectname=rpm-gitoverlay-1497868338.320130 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6b1c536b80>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/prune-dist-git.py", line 50, in <module>
    client.project_proxy.get(username, projectname)
  File "/usr/lib/python3.9/site-packages/copr/v3/helpers.py", line 62, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/copr/v3/proxies/project.py", line 34, in get
    response = request.send()
  File "/usr/lib/python3.9/site-packages/copr/v3/requests.py", line 54, in send
    raise CoprRequestException("Unable to connect to {0}.".format(self.api_base_url))
copr.v3.exceptions.CoprRequestException: Unable to connect to https://copr.fedorainfracloud.org/api_3/.