create copr with lighttpd group
addressing:
Error in PREIN scriptlet in rpm package copr-backend-1.1-1.git.47.2255ac2.el6.noarch
useradd: group 'apache' does not exist
passwd: Unknown user name 'copr'.
error: %pre(copr-backend-1.1-1.git.47.2255ac2.el6.noarch) scriptlet failed, exit status 252