frontend: fix one more traceback in builder-live.log link
When SRPM build succeeds but import fails - the build is "failed" so it
is finished, but it doesn't have result dir yet.  Trying to
os.path.join(None, str()) throws this:
TypeError: expected str, bytes or os.PathLike object, not NoneType

Merges: #1058