backend: add change-storage support for persistent projects
See PR #4164

It left our migration script in a broken state

    $ copr-change-storage --src backend --dst pulp --project frostyx/foo
    Traceback (most recent call last):
      File "/opt/copr/backend/run/copr-change-storage", line 370, in <module>
        main()
        ~~~~^^
      File "/opt/copr/backend/run/copr-change-storage", line 347, in main
        change_storage_for_project(args.project, args.dst, config)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/copr/backend/run/copr-change-storage", line 154, in change_storage_for_project
        storage = PulpStorage(
            owner, subproject, appstream, devel, config, log)
      File "/opt/copr/backend/copr_backend/storage.py", line 301, in __init__
        super().__init__(*args, **kwargs)
        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
    TypeError: Storage.__init__() missing 1 required positional argument: 'log'

Don't get confused by to missing `log` argument. Log is being passed, it's just
that we forgot on the `persistent` argument before that.