frontend: return a user friendly error when modulemd is not ok
Fix #1382

Instead of a typical last-resort exception message

    Error: Request wasn't successful, there is probably a bug in the API code

Print something more user-frinedly, e.g.

    Error: Unsupported or malformed modulemd yaml - Missing required option
    data.summary

    Error: Invalid modulemd yaml - Provided YAML did not begin with
    a module document

    Error: Invalid modulemd yaml - Parser error

Merges: #1384