frontend: fix tests that fail in Fedora Rawhide chroots
The errors were multiple occurences of those two

    TypeError: missing a required argument: 'mc_flask_g'
    TypeError: missing a required argument: 'send_mail'

I am not sure about the exact cause but it looks like mocked
`flask.g` doesn't play well with `@new_app_context`.