if directory does not exist, do not try to delete it
addressing:
Process jobgrab:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/share/copr/copr-be.py", line 104, in run
    self.fetch_jobs()
  File "/usr/share/copr/copr-be.py", line 97, in fetch_jobs
    ao.run()
  File "/usr/share/copr/backend/actions.py", line 51, in run
    for chroot in os.listdir(path):
OSError: [Errno 2] No such file or directory: '/var/lib/copr/public_html/results/asamalik/test-project'