[backend] in case of error the output is in e.output
addressing:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/share/copr/backend/dispatcher.py", line 313, in run
    ip = self.spawn_instance()
  File "/usr/share/copr/backend/dispatcher.py", line 168, in spawn_instance
    sys.stderr.write("%s\n" % result)
UnboundLocalError: local variable 'result' referenced before assignment
Process worker-builder:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/share/copr/backend/dispatcher.py", line 313, in run
    ip = self.spawn_instance()
  File "/usr/share/copr/backend/dispatcher.py", line 168, in spawn_instance
    sys.stderr.write("%s\n" % result)
UnboundLocalError: local variable 'result' referenced before assignment
Process worker-builder:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/share/copr/backend/dispatcher.py", line 313, in run
    ip = self.spawn_instance()
  File "/usr/share/copr/backend/dispatcher.py", line 168, in spawn_instance
    sys.stderr.write("%s\n" % result)
UnboundLocalError: local variable 'result' referenced before assignment
Process worker-builder:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/share/copr/backend/dispatcher.py", line 313, in run
    ip = self.spawn_instance()
  File "/usr/share/copr/backend/dispatcher.py", line 168, in spawn_instance
    sys.stderr.write("%s\n" % result)
UnboundLocalError: local variable 'result' referenced before assignment
Traceback (most recent call last):
  File "/usr/share/copr/copr-be.py", line 306, in <module>
Terminating on signal 15
    main(sys.argv[1:])
  File "/usr/share/copr/copr-be.py", line 297, in main
    cbe.run()
  File "/usr/share/copr/copr-be.py", line 240, in run
    raise errors.CoprBackendError, "Worker died unexpectedly, exiting"
backend.errors.CoprBackendError: Worker died unexpectedly, exiting
close failed in file object destructor:
sys.excepthook is missing