manage.py requires python-requests
addressing:
$ ./manage.py "create_db" "--alembic" alembic.ini
Traceback (most recent call last):
  File "./manage.py", line 18, in <module>
    from run import generate_repo_packages
  File "/usr/share/copr/coprs_frontend/run/generate_repo_packages.py", line 14, in <module>
    import requests
ImportError: No module named requests