Revert "[frontend] try again if whoosh does not get lock"
This reverts commit 28aced9cb3e360c6cb83cce7f561d4e03afd900f.

This is no longer needed as flask-whoshee handle timeout properly now.

And it is causing this traceback:

 ERROR:coprs:Exception on /backend/update/ [POST]
 Traceback (most recent call last):
   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
     response = self.full_dispatch_request()
   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
     rv = self.handle_user_exception(e)
   File "/usr/share/copr/coprs_frontend/coprs/rest_api/__init__.py", line 44, in error_router
     return original_handler(e)
   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
     reraise(exc_type, exc_value, tb)
   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
     rv = self.dispatch_request()
   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
     return self.view_functions[rule.endpoint](**req.view_args)
   File "/usr/share/copr/coprs_frontend/coprs/views/misc.py", line 293, in decorated_function
     return f(*args, **kwargs)
   File "/usr/share/copr/coprs_frontend/coprs/views/backend_ns/backend_general.py", line 206, in update
     db.session.commit()
   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
     return getattr(self.registry(), name)(*args, **kwargs)
   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 801, in commit
     self.transaction.commit()
   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 390, in commit
     self._assert_active(prepared_ok=True)
   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 196, in _assert_active
     "This session is in 'committed' state; no further "
 InvalidRequestError: This session is in 'committed' state; no further SQL can be emitted within this transaction.