rpmbuild: don't try to log that logger is not ready yet
This causes a recursion error, crashing the whole script

    File "/usr/lib64/python3.12/logging/__init__.py", line 1762, in callHandlers
      hdlr.handle(record)
    File "/usr/lib64/python3.12/logging/__init__.py", line 1700, in handle
      self.callHandlers(record)
    File "/usr/lib64/python3.12/logging/__init__.py", line 1762, in callHandlers
      hdlr.handle(record)
    File "/usr/lib64/python3.12/logging/__init__.py", line 1695, in handle
      maybe_record = self.filter(record)
                     ^^^^^^^^^^^^^^^^^^^
    RecursionError: maximum recursion depth exceeded