rpmbuild: common: Fixing copr-common version
We need the new version of copr-common package because this test.

    def download_srpm(self):
            basename = os.path.basename(self.parsed_url.path)
            filename = os.path.join(self.resultdir, basename)
    >       response = self.request.get(self.url, stream=True)
    E       TypeError: SafeRequest.get() got an unexpected keyword argument 'stream'