frontend: use context manager for SQLAlchemy execute
See #3130

    AttributeError: 'Engine' object has no attribute 'execute'

And also use text for raw SQL commands

    Use the text() construct, or the Connection.exec_driver_sql()
    method to invoke a driver-level SQL string.

And finially setting `future=True` which is going to be passed to
`create_engine` by Flask-SQLAlchemy to ensure compatibility between
SQLAlchemy 1.x and 2.0. Otherwise we would get

    AttributeError: 'Connection' object has no attribute 'commit'