cli: pypi package needs to depend on 'humanize'
$ copr-cli
Traceback (most recent call last):
  File "/home/praiskup/test/bin/copr-cli", line 6, in <module>
    from copr_cli.main import main
  File "/home/praiskup/test/lib/python3.7/site-packages/copr_cli/main.py", line 36, in <module>
    from .util import ProgressBar, json_dumps
  File "/home/praiskup/test/lib/python3.7/site-packages/copr_cli/util.py", line 3, in <module>
    import humanize
ModuleNotFoundError: No module named 'humanize'